FROM ulsmith/debian-apache-php
MAINTAINER Mark <mark@markmulder.net>

# Copy your files to working directory /var/www/html
# ADD ./ /var/www/html
# RUN chmod -R 0755 /var/www/html

EXPOSE 80
CMD ["/run.sh"]